# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import backtest_pb2 as backtest__pb2
from . import common_pb2 as common__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in backtest_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BacktestPluginStub(object):
    """=============================================================================
    Backtest Plugin Service (Core -> Plugin)
    =============================================================================

    BacktestPlugin is implemented by backtest engine plugins.
    Core calls this service to request backtests.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RunBacktest = channel.unary_stream(
                '/quantnexus.BacktestPlugin/RunBacktest',
                request_serializer=backtest__pb2.BacktestRequest.SerializeToString,
                response_deserializer=backtest__pb2.BacktestProgress.FromString,
                _registered_method=True)
        self.GetResult = channel.unary_unary(
                '/quantnexus.BacktestPlugin/GetResult',
                request_serializer=backtest__pb2.ResultRequest.SerializeToString,
                response_deserializer=backtest__pb2.BacktestResult.FromString,
                _registered_method=True)
        self.CancelBacktest = channel.unary_unary(
                '/quantnexus.BacktestPlugin/CancelBacktest',
                request_serializer=backtest__pb2.CancelRequest.SerializeToString,
                response_deserializer=backtest__pb2.CancelResult.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/quantnexus.BacktestPlugin/Ping',
                request_serializer=common__pb2.PingRequest.SerializeToString,
                response_deserializer=common__pb2.PingResponse.FromString,
                _registered_method=True)
        self.GetCapabilities = channel.unary_unary(
                '/quantnexus.BacktestPlugin/GetCapabilities',
                request_serializer=common__pb2.Empty.SerializeToString,
                response_deserializer=backtest__pb2.BacktestCapabilities.FromString,
                _registered_method=True)


class BacktestPluginServicer(object):
    """=============================================================================
    Backtest Plugin Service (Core -> Plugin)
    =============================================================================

    BacktestPlugin is implemented by backtest engine plugins.
    Core calls this service to request backtests.
    """

    def RunBacktest(self, request, context):
        """Run a backtest (streaming progress updates)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetResult(self, request, context):
        """Get the result of a completed backtest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelBacktest(self, request, context):
        """Cancel a running backtest
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """Health check
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCapabilities(self, request, context):
        """Get plugin capabilities
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BacktestPluginServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RunBacktest': grpc.unary_stream_rpc_method_handler(
                    servicer.RunBacktest,
                    request_deserializer=backtest__pb2.BacktestRequest.FromString,
                    response_serializer=backtest__pb2.BacktestProgress.SerializeToString,
            ),
            'GetResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetResult,
                    request_deserializer=backtest__pb2.ResultRequest.FromString,
                    response_serializer=backtest__pb2.BacktestResult.SerializeToString,
            ),
            'CancelBacktest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelBacktest,
                    request_deserializer=backtest__pb2.CancelRequest.FromString,
                    response_serializer=backtest__pb2.CancelResult.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=common__pb2.PingRequest.FromString,
                    response_serializer=common__pb2.PingResponse.SerializeToString,
            ),
            'GetCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCapabilities,
                    request_deserializer=common__pb2.Empty.FromString,
                    response_serializer=backtest__pb2.BacktestCapabilities.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantnexus.BacktestPlugin', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantnexus.BacktestPlugin', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BacktestPlugin(object):
    """=============================================================================
    Backtest Plugin Service (Core -> Plugin)
    =============================================================================

    BacktestPlugin is implemented by backtest engine plugins.
    Core calls this service to request backtests.
    """

    @staticmethod
    def RunBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/quantnexus.BacktestPlugin/RunBacktest',
            backtest__pb2.BacktestRequest.SerializeToString,
            backtest__pb2.BacktestProgress.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.BacktestPlugin/GetResult',
            backtest__pb2.ResultRequest.SerializeToString,
            backtest__pb2.BacktestResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelBacktest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.BacktestPlugin/CancelBacktest',
            backtest__pb2.CancelRequest.SerializeToString,
            backtest__pb2.CancelResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.BacktestPlugin/Ping',
            common__pb2.PingRequest.SerializeToString,
            common__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.BacktestPlugin/GetCapabilities',
            common__pb2.Empty.SerializeToString,
            backtest__pb2.BacktestCapabilities.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
