# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import common_pb2 as common__pb2
from . import plugin_pb2 as plugin__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in plugin_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginManagerStub(object):
    """=============================================================================
    Plugin Manager Service (Core -> Plugin communication)
    =============================================================================

    PluginManager is implemented by the Core.
    Plugins call this service to register themselves.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/quantnexus.PluginManager/Register',
                request_serializer=plugin__pb2.PluginInfo.SerializeToString,
                response_deserializer=plugin__pb2.RegistrationResult.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/quantnexus.PluginManager/Heartbeat',
                request_serializer=plugin__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=plugin__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.Unregister = channel.unary_unary(
                '/quantnexus.PluginManager/Unregister',
                request_serializer=plugin__pb2.UnregisterRequest.SerializeToString,
                response_deserializer=plugin__pb2.UnregisterResult.FromString,
                _registered_method=True)
        self.ReportStatus = channel.unary_unary(
                '/quantnexus.PluginManager/ReportStatus',
                request_serializer=plugin__pb2.PluginStatus.SerializeToString,
                response_deserializer=common__pb2.Response.FromString,
                _registered_method=True)


class PluginManagerServicer(object):
    """=============================================================================
    Plugin Manager Service (Core -> Plugin communication)
    =============================================================================

    PluginManager is implemented by the Core.
    Plugins call this service to register themselves.
    """

    def Register(self, request, context):
        """Register a plugin with the core
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Send heartbeat to indicate plugin is alive
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Unregister(self, request, context):
        """Unregister a plugin (graceful shutdown)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportStatus(self, request, context):
        """Report plugin status/metrics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=plugin__pb2.PluginInfo.FromString,
                    response_serializer=plugin__pb2.RegistrationResult.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=plugin__pb2.HeartbeatRequest.FromString,
                    response_serializer=plugin__pb2.HeartbeatResponse.SerializeToString,
            ),
            'Unregister': grpc.unary_unary_rpc_method_handler(
                    servicer.Unregister,
                    request_deserializer=plugin__pb2.UnregisterRequest.FromString,
                    response_serializer=plugin__pb2.UnregisterResult.SerializeToString,
            ),
            'ReportStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportStatus,
                    request_deserializer=plugin__pb2.PluginStatus.FromString,
                    response_serializer=common__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'quantnexus.PluginManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('quantnexus.PluginManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginManager(object):
    """=============================================================================
    Plugin Manager Service (Core -> Plugin communication)
    =============================================================================

    PluginManager is implemented by the Core.
    Plugins call this service to register themselves.
    """

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.PluginManager/Register',
            plugin__pb2.PluginInfo.SerializeToString,
            plugin__pb2.RegistrationResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.PluginManager/Heartbeat',
            plugin__pb2.HeartbeatRequest.SerializeToString,
            plugin__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Unregister(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.PluginManager/Unregister',
            plugin__pb2.UnregisterRequest.SerializeToString,
            plugin__pb2.UnregisterResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/quantnexus.PluginManager/ReportStatus',
            plugin__pb2.PluginStatus.SerializeToString,
            common__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
